### ISSUE TITLE
Problem getting workadventure-map-starter-kit up & running

### ISSUE THREAD

**Issue by netzwerkgoettin** [nolway/wa-map-optimizer-vite#1]
Hi,

I try to get `workadventure-map-starter-kit` up & running, but I ran into an issue with `wa-map-optimizer-vite`.

```
> workadventure-map-starter-kit@3.0.3 dev /var/www/html
> vite

failed to load config from /var/www/html/vite.config.ts
error when starting dev server:
/var/www/html/node_modules/wa-map-optimizer-vite/dist/index.js:77
            if (!map?.properties) {
                     ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/html/vite.config.ts:27:36)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.require.extensions.<computed> [as .ts] (/var/www/html/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:61963:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! workadventure-map-starter-kit@3.0.3 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the workadventure-map-starter-kit@3.0.3 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/docker/.npm/_logs/2022-06-16T13_56_36_376Z-debug.log
```

This debug log file is [attached](https://github.com/nolway/wa-map-optimizer-vite/files/8919453/2022-06-16T13_56_36_376Z-debug.log).

The `maps` container is part of my `docker-compose.yml`:
```yaml
  maps:
    image: thecodingmachine/nodejs:12-apache
    container_name: "wa-workadventure-maps"
    hostname: "maps"
    environment:
      DEBUG_MODE: "${DEBUG_MODE}"
      HOST: "0.0.0.0"
      NODE_ENV: development
      STARTUP_COMMAND_0: sudo a2enmod headers
      STARTUP_COMMAND_1: npm install
      STARTUP_COMMAND_2: npm run dev &
    volumes:
      - ./maps:/var/www/html
    labels:
      - "traefik.http.routers.maps.rule=Host(`${MAPS_HOST}`)"
      - "traefik.http.routers.maps.entryPoints=web"
      - "traefik.http.services.maps.loadbalancer.server.port=80"
    networks:
      workadventure:
        aliases:
          - "${MAPS_HOST}"
```

Please let me know if I can provide you further information.

Regards,
  Marianne
